name: Laravel
on:
  pull_request:
    branches: [ master ]
    types: [close]

jobs:
  deploy_laravel:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      if: github.event.pull_request.merged == 'true'
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd Pleio/pleio.lift.environment.2022/src_feature && sh deploy.sh
