name: Laravel
on:
  pull_request:
    branches: [ master ]

jobs:
  pull-request-laravel-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
    - name: Executing remote ssh commands using ssh file
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_AUTO }}
        username: ${{ secrets.USERNAME_AUTO }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
           whoami
           ls -al
