name: Laravel
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    # types: [created]

jobs:
  pull-request-laravel-testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --ignore-platform-reqs --no-scripts
    - name: Execute Unit tests via PHPUnit
      run: vendor/bin/phpunit tests/Unit
    - name: Run command on remote servers
      uses: appleboy/ssh-action@v0.1.7
      if: success()
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd Pleio/pleio.lift.environment.2022/src_feature && sh testing.sh
          result=$?
          echo "Result: $result"
          exit $result
    - name: Check result
      if: ${{ steps.run_command.outputs.result != 0 }}
      run: exit 1
