name: Laravel
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened]

jobs:
  pull-request-laravel-testing:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options:
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3.33
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      env:
        COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH}}"} }'
      run: composer install --ignore-platform-reqs --no-scripts
    - name: Execute Unit tests via PHPUnit
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: vendor/bin/phpunit tests/Unit
