name: Laravel
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  push-laravel-testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      if: github.event.pull_request.merged == true
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
